### ISSUE TITLE
Display mana tap message only once for multiple tapped mana

### ISSUE THREAD

**Issue by PranjalBishtNX** [nitro-x/dm-ocg-octgn#40]
Instead of "nitrox taps xyz in their mana zone" 10 times when you select and tap 10 mana together, game should display: "nitrox taps 10 mana" once.

**Comment by nitro-x** [comment]
Instead of "nitrox taps xyz in their mana zone" 10 times when you select and tap 10 mana together, game should display: "nitrox taps 10 mana" once.

**Comment by PranjalBishtNX** [comment]
Done, Implemented with batchExecute on action tap.
https://github.com/nitro-x/dm-ocg-octgn/commit/47ceb53a34d463a85f528c30d48b11502eea8e75
